// ============================================================
// NexusPay – Mock data for UI development
// Replace with real Supabase queries when backend is connected
// ============================================================

import type { DashboardSummary, UpcomingPayment } from '@/types'

export const mockSummary: DashboardSummary = {
  total_month: 887.99,
  total_paid: 30.00,
  total_pending: 857.99,
  currency: 'USD',
}

export const mockUpcomingPayments: UpcomingPayment[] = [
  {
    id: 'pe-1',
    payment_id: 'p-1',
    user_id: 'u-1',
    year: 2026,
    month: 6,
    due_date: '2026-06-01',
    paid_at: null,
    paid_by: null,
    payment_method: null,
    amount_paid: null,
    status: 'overdue',
    created_at: '',
    updated_at: '',
    days_until_due: -1,
    payment: {
      id: 'p-1',
      user_id: 'u-1',
      space_id: null,
      category_id: 'c-1',
      name: 'Alquiler',
      amount: 800.00,
      currency: 'USD',
      due_day: 1,
      is_recurring: true,
      notes: null,
      created_at: '',
      updated_at: '',
      category: { id: 'c-1', user_id: 'u-1', name: 'Vivienda', description: null, icon: 'home', color: '#3B82F6', created_at: '' },
    },
  },
  {
    id: 'pe-2',
    payment_id: 'p-2',
    user_id: 'u-1',
    year: 2026,
    month: 6,
    due_date: '2026-06-02',
    paid_at: null,
    paid_by: null,
    payment_method: null,
    amount_paid: null,
    status: 'pending',
    created_at: '',
    updated_at: '',
    days_until_due: 0,
    payment: {
      id: 'p-2',
      user_id: 'u-1',
      space_id: null,
      category_id: 'c-2',
      name: 'Internet',
      amount: 45.00,
      currency: 'USD',
      due_day: 2,
      is_recurring: true,
      notes: null,
      created_at: '',
      updated_at: '',
      category: { id: 'c-2', user_id: 'u-1', name: 'Servicios', description: null, icon: 'wifi', color: '#10B981', created_at: '' },
    },
  },
  {
    id: 'pe-3',
    payment_id: 'p-3',
    user_id: 'u-1',
    year: 2026,
    month: 6,
    due_date: '2026-06-05',
    paid_at: null,
    paid_by: null,
    payment_method: null,
    amount_paid: null,
    status: 'pending',
    created_at: '',
    updated_at: '',
    days_until_due: 3,
    payment: {
      id: 'p-3',
      user_id: 'u-1',
      space_id: null,
      category_id: 'c-3',
      name: 'Netflix',
      amount: 12.99,
      currency: 'USD',
      due_day: 5,
      is_recurring: true,
      notes: null,
      created_at: '',
      updated_at: '',
      category: { id: 'c-3', user_id: 'u-1', name: 'Suscripción', description: null, icon: 'tv', color: '#EC4899', created_at: '' },
    },
  },
  {
    id: 'pe-4',
    payment_id: 'p-4',
    user_id: 'u-1',
    year: 2026,
    month: 6,
    due_date: '2026-05-28',
    paid_at: '2026-05-28T10:00:00Z',
    paid_by: 'u-1',
    payment_method: 'debit',
    amount_paid: 30.00,
    status: 'paid',
    created_at: '',
    updated_at: '',
    days_until_due: -4,
    payment: {
      id: 'p-4',
      user_id: 'u-1',
      space_id: null,
      category_id: 'c-4',
      name: 'Gimnasio',
      amount: 30.00,
      currency: 'USD',
      due_day: 28,
      is_recurring: true,
      notes: null,
      created_at: '',
      updated_at: '',
      category: { id: 'c-4', user_id: 'u-1', name: 'Salud', description: null, icon: 'dumbbell', color: '#8B5CF6', created_at: '' },
    },
  },
]
